exports.meals = [
    {name: 'Banana Spinach Pancake', referenceURL: 'https://www.yummytoddlerfood.com/banana-spinach-pancakes', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/IKSvLr9.jpg'},
    {name: 'Sweet Potato Pancakes', referenceURL: 'https://www.theconsciousplantkitchen.com/sweet-potato-pancakes-baby/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/SZkiYoa.png'},
    {name: 'Banana Waffles', referenceURL: 'https://apeachyplate.com/waffles-for-babies/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/PYnS5Lc.jpg'},
    {name: 'Banana Bread', referenceURL: 'https://www.healthylittlefoodies.com/banana-bread/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/LEDDZEb.png'},
    {name: 'Banana Bread', referenceURL: 'https://www.healthylittlefoodies.com/banana-bread/', mealType: 'Snack', imgURL: 'https://i.imgur.com/LEDDZEb.png'},
    {name: 'Blueberry Muffin', referenceURL: 'https://www.healthylittlefoodies.com/baby-blueberry-muffins/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/WGHqDXx.jpg'},
    {name: 'Blueberry Muffin', referenceURL: 'https://www.healthylittlefoodies.com/baby-blueberry-muffins/', mealType: 'Snack', imgURL: 'https://i.imgur.com/WGHqDXx.jpg'},
    {name: 'French Toast', referenceURL: 'https://www.myfussyeater.com/baby-french-toast-eggy-banana-bread/ ', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/qnhbRMh.png'},
    {name: 'Coconut Chia Pudding', referenceURL: 'https://www.yummytoddlerfood.com/coconut-chia-pudding/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/JS2VsWL.jpg'},
    {name: 'Coconut Chia Pudding', referenceURL: 'https://www.yummytoddlerfood.com/coconut-chia-pudding/', mealType: 'Snack', imgURL: 'https://i.imgur.com/JS2VsWL.jpg'},
    {name: 'Egg Muffins', referenceURL: 'https://babyfoode.com/blog/toddler-breakfast-egg-cups-4-tasty-ways/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/kvH4GXd.png'},
    {name: 'Tuna Omelet', referenceURL: 'https://www.healthylittlefoodies.com/tuna-frittata/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/rgPahwQ.jpg'},
    {name: 'Tuna Omelet', referenceURL: 'https://www.healthylittlefoodies.com/tuna-frittata/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/rgPahwQ.jpg'},
    {name: 'Apple Cinnamon Waffle', referenceURL: 'https://www.healthylittlefoodies.com/apple-waffles/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/DFpE9tz.jpg'},
    {name: 'Blueberry Banana Waffle', referenceURL: 'https://www.healthylittlefoodies.com/banana-blueberry-waffles/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/7Oc3t76.jpg'},
    {name: 'Strawberry Pancakes', referenceURL: 'https://www.yummytoddlerfood.com/fluffy-strawberry-pancakes/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/CkujELK.jpg'},
    {name: 'Apple Fritters', referenceURL: 'https://feedingtinybellies.com/apple-fritters-for-babies/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/kWNQrYw.png'},
    {name: 'Apple Fritters', referenceURL: 'https://feedingtinybellies.com/apple-fritters-for-babies/', mealType: 'Snack', imgURL: 'https://i.imgur.com/kWNQrYw.png'},
    {name: 'Vegetable Savory Muffins', referenceURL: 'https://www.healthylittlefoodies.com/vegetable-savoury-muffins/', mealType: 'Breakfast', imgURL: 'https://i.imgur.com/tUQ66v0.png'},
    {name: 'Vegetable Savory Muffins', referenceURL: 'https://www.healthylittlefoodies.com/vegetable-savoury-muffins/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/tUQ66v0.png'},
    {name: 'Tuna Tomato Pasta', referenceURL: 'https://www.healthylittlefoodies.com/tuna-tomato-pasta/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/nOj0ve7.jpg'},
    {name: 'Tuna Tomato Pasta', referenceURL: 'https://www.healthylittlefoodies.com/tuna-tomato-pasta/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/nOj0ve7.jpg'},
    {name: 'Baby Bolognese', referenceURL: 'https://www.healthylittlefoodies.com/extra-veggies-bolognese/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/Jg6T4HH.jpg'},
    {name: 'Baby Bolognese', referenceURL: 'https://www.healthylittlefoodies.com/extra-veggies-bolognese/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/Jg6T4HH.jpg'},
    {name: 'Chicken Noodle Soup', referenceURL: 'https://www.yummytoddlerfood.com/chicken-noodle-soup-for-kids/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/kP5wSPW.jpg'},
    {name: 'Chicken Noodle Soup', referenceURL: 'https://www.yummytoddlerfood.com/chicken-noodle-soup-for-kids/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/kP5wSPW.jpg'},
    {name: 'Vegetable Rice', referenceURL: 'https://babyfoode.com/blog/easy-veggie-fried-rice-for-baby-toddler/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/SKsNJlP.jpg'},
    {name: 'Vegetable Rice', referenceURL: 'https://babyfoode.com/blog/easy-veggie-fried-rice-for-baby-toddler/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/SKsNJlP.jpg'},
    {name: 'Vegetable Fritters', referenceURL: 'https://www.healthylittlefoodies.com/rainbow-fritters/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/1BWrZ6N.jpg'},
    {name: 'Vegetable Fritters', referenceURL: 'https://www.healthylittlefoodies.com/rainbow-fritters/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/1BWrZ6N.jpg'},
    {name: 'Chicken Nuggets', referenceURL: 'https://www.yummytoddlerfood.com/chicken-nuggets-with-sweet-potato/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/A2xDbFh.png'},
    {name: 'Chicken Nuggets', referenceURL: 'https://www.yummytoddlerfood.com/chicken-nuggets-with-sweet-potato/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/A2xDbFh.png'},
    {name: 'Vegetable Chicken Bites', referenceURL: 'https://thenaturalnurturer.com/veggie-loaded-chicken-bites/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/KO64mwF.jpg'},
    {name: 'Vegetable Chicken Bites', referenceURL: 'https://thenaturalnurturer.com/veggie-loaded-chicken-bites/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/KO64mwF.jpg'},
    {name: 'Chicken Tenders', referenceURL: 'https://www.yummytoddlerfood.com/baked-chicken-tenders/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/6Cp2j93.jpg'},
    {name: 'Chicken Tenders', referenceURL: 'https://www.yummytoddlerfood.com/baked-chicken-tenders/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/6Cp2j93.jpg'},
    {name: 'Broccoli Tots', referenceURL: 'https://www.yummytoddlerfood.com/broccoli-tots/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/AqKWzq3.png'},
    {name: 'Broccoli Tots', referenceURL: 'https://www.yummytoddlerfood.com/broccoli-tots/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/AqKWzq3.png'},
    {name: 'Salmon Croquettes', referenceURL: 'https://www.healthylittlefoodies.com/salmon-croquettes/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/9OV4FzB.png'},
    {name: 'Salmon Croquettes', referenceURL: 'https://www.healthylittlefoodies.com/salmon-croquettes/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/9OV4FzB.png'},
    {name: 'Baked Salmon', referenceURL: 'https://www.dessertfortwo.com/baby-food-salmon-potatoes-colcannon/', mealType: 'Lunch', imgURL: 'https://i.imgur.com/KkkBNuv.png'},
    {name: 'Baked Salmon', referenceURL: 'https://www.dessertfortwo.com/baby-food-salmon-potatoes-colcannon/', mealType: 'Dinner', imgURL: 'https://i.imgur.com/KkkBNuv.png'},
    {name: 'Frozen Yogurt Bark', referenceURL: 'https://feelgoodfoodie.net/recipe/frozen-yogurt-bark/', mealType: 'Snack', imgURL: 'https://i.imgur.com/w47Epic.png'},
    {name: 'Healthy Popsicle', referenceURL: 'https://babyfoode.com/blog/7-healthy-popsicles-for-baby-toddler-made-with-fruits-veggies/', mealType: 'Snack', imgURL: 'https://i.imgur.com/T22jCvo.png'}
  ];
  
